FROM golang:latest as builder

# Current Working Directory
WORKDIR /app

# go cert.pem and key.pem files
COPY *.pem ./
ENV GOPATH /

# go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o web /app/web
#RUN go install /app/loadbalancer

FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/loadbalancer .

# Expose port 3000
EXPOSE 3000

CMD ["./web"] 